services:
  saf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saf_erp_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://flotas:Mineria99*@187.77.57.116:5441/flotas
      - JWT_SECRET=saf-f1t02-jwt-secret-2026-secure-token-key-anchillo
      - NEXT_PUBLIC_APP_URL=https://aimachristian-administraciondeflotas.ajcxjb.easypanel.host
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=pedroanchillo185@gmail.com
      - SMTP_PASS=klhg uvpb pfir wvyu
      - SMTP_FROM=SAF Flotas <pedroanchillo185@gmail.com>
      - NODE_ENV=production
